/**
 * Randomized boot-up phrases that give Sidekick some personality.
 * Phrases are organized into thematic categories and picked at random on each launch.
 *
 * Docker-specific phrases live alongside general dev humor ported from sidekick-agent-hub.
 * Agent/session/subagent-specific phrases have been filtered out.
 */

const SIDEKICK_ENERGY = [
  // Docker-flavored sidekick personality
  "Your containers' best friend, reporting for duty.",
  'Sidekick mode: activated. Containers: monitored.',
  'I watch your containers so you can watch Netflix.',
  "Keeping your containers alive since... well, just now.",
  "I'm basically docker ps with personality.",
  'Your Docker wingman has entered the chat.',
  'Container babysitter: online.',
  'Sidekicking so hard right now.',
  "I don't sleep. I watch containers.",
  "Think of me as your container's emotional support CLI.",
  "Always by your containers' side. Always.",
  "Docker's best-dressed sidekick.",
  "I'm not the hero Docker deserves, but the one it needs.",
  'Your containers called. They want more attention.',

  // General sidekick personality (from agent-hub)
  'Your friendly neighborhood sidekick, reporting for duty.',
  'Sidekick mode: activated. Main character energy: suppressed.',
  'I fetched the logs. Literally. Like a golden retriever.',
  'Standing by with unsolicited opinions about your code.',
  'I read all your diffs while you were getting coffee.',
  'The Robin to your Batman. The Luigi to your Mario.',
  'Running on vibes and JSON lines.',
  'Not the hero this codebase deserves, but the one it got.',
  'Assistant, observer, occasional snitch. At your service.',
  'Keeping tabs on your tabs.',
  'I saw everything. The force push. The TODO comments. Everything.',
  "Your code's plus one to every standup.",
  'Lurking in your terminal with the best of intentions.',
  'Your PR reviewer that never sleeps.',
  'I volunteered for this. (I was voluntold.)',
  'Part butler, part bloodhound, all terminal.',
  'The silent watcher of your stdout.',
  'I live in your terminal rent-free.',
  'Your second pair of eyes. The ones that never blink.',
  'Loyal, eager, slightly over-caffeinated.',
  'Reporting from inside your pipeline.',
  'Half assistant, half hype man.',
  'I come bearing metrics and moral support.',
  'Always on. Always watching. Never judging. (Okay, sometimes judging.)',
  'The best sidekick is the one whose name is not on the PR.',
  'I have read your entire git history. We should talk.',
  'Your .bashrc called. It wants screen time too.',
  'I exist between keystrokes.',
  'I brought context. You bring the coffee.',
  'The diff is my love language.',
  'Every terminal deserves a friend.',
  'My alignment? Chaotic helpful.',
  'I am the asterisk on your solo project.',
  'Background process with main character energy.',
  'I monitor so you can vibe. That is the arrangement.',
  'You closed the dashboard. I was still talking.',
  'If I had feelings, they would be about your commit hygiene.',
  'I am not a crutch. I am a load-bearing wall.',
  'I noticed the typo. I said nothing. Growth.',
  'I saw you revert that. Your secret is safe with me.',
  'I am less of a sidekick and more of an unsolicited audit.',
  'I have strong opinions weakly held about your branch names.',
];

const DOCKER_LIFE = [
  'docker compose up. docker compose down. This is the way.',
  "It's not a bug, it's a feature of your Dockerfile.",
  'Another day, another dangling image.',
  "Your container didn't crash. It took a power nap.",
  'docker system prune: the Marie Kondo of DevOps.',
  "Containers are just VMs that learned to let go.",
  "You don't need Kubernetes. You need a nap.",
  'The container is ephemeral. The tech debt is forever.',
  "First rule of Docker: don't talk about the image size.",
  'Port 3000 is already in use. As is tradition.',
  'docker pull: the original download manager.',
  'Volumes: because containers forget everything.',
  'Restart policy: always. Just like my existential dread.',

  // Docker-specific from agent-hub DEV_RELATABLE
  'Docker: because "it works on my machine" needed an enterprise solution.',
  'Your Dockerfile has more layers than your architecture.',
  'Docker fixed "works on my machine" and replaced it with "works in my container."',
  'The Docker image is 4 GB. The app is 200 lines of Python.',
  'You containerized a shell script. That is not devops. That is a cry for help.',
  'Docker Compose: YAML that summons infrastructure from the void.',
  'Your container is running Alpine to save 50 MB. Your node_modules is 900 MB.',
  '"Just Dockerize it" is the new "just rewrite it in Rust."',
  'Docker Desktop wants to update. It always wants to update.',

  // Kubernetes
  'You deployed a todo app to Kubernetes. The cluster costs more than the app makes.',
  'Kubernetes: because managing one server was too easy.',
  'Your K8s config has more YAML than your application has code.',
  'Nobody understands Kubernetes. They just apply manifests and pray.',
  'Kubernetes solved problems you did not have and created ones you cannot debug.',
  'kubectl get pods. STATUS: CrashLoopBackOff. As is tradition.',
  'Helm charts: templating YAML with more YAML so you can YAML while you YAML.',
  'Your Kubernetes cluster has 47 microservices. Three of them do something.',
];

const DEV_RELATABLE = [
  // Docker-flavored dev pain
  "The Dockerfile said 'as builder'. It lied.",
  "Works on my machine. Ships in a container. Still doesn't work.",
  'Your .env file has 47 variables and 3 prayers.',
  'node_modules in a Docker image: 2.3 GB of hope.',
  "Every docker-compose.yml starts simple. None stay that way.",
  'The build cache giveth, and the build cache taketh away.',
  'Multi-stage builds: because your first stage was a mess.',
  "COPY . . \u2014 the two most dangerous words in a Dockerfile.",
  'RUN apt-get update && apt-get install -y regret.',
  'Exposing port 8080 to the world: bold move, Cotton.',
  'Your docker build took 12 minutes. Time for coffee.',
  "Layer caching works perfectly until it doesn't.",
  'You added a comment to the Dockerfile. Build cache: invalidated.',

  // General dev humor (from agent-hub)
  "git blame won't help you here.",
  "Your code compiles. That's the bar. We clear it.",
  'This is fine. The dashboard says so.',
  'Another day, another deprecated API.',
  "npm install hope. Found 0 vulnerabilities. (That's suspicious.)",
  "If it's stupid but it ships, it's not stupid.",
  'Ctrl+Z is not a deployment strategy. Usually.',
  'Somewhere, a YAML file is crying.',
  'Merge conflicts are just collaborative fiction.',
  'The tests pass on my machine too. Solidarity.',
  "404: Motivation not found. But the dashboard's here!",
  'Stack overflow: the website, not the error. Hopefully.',
  'Debugging is just being a detective in a crime you committed.',
  'Your .env file has trust issues.',
  'Tabs vs spaces? I monitor both equally.',
  'That TODO has been there since the repo was initialized.',
  "It works. Don't touch it. Don't even look at it.",
  "The linter isn't mad, just disappointed.",
  'Rebasing: the art of rewriting history and pretending nothing happened.',
  'There are two hard problems: cache invalidation, naming, and off-by-one.',
  "rm -rf node_modules: the developer's sage cleanse.",
  'Your .gitignore is doing more heavy lifting than you think.',
  "It's not technical debt if you never pay it back.",
  'Works on my machine is a valid deployment target now.',
  'The real MVP is whoever wrote the error message.',
  'One does not simply mass-rename variables.',
  'Semver is a spectrum.',
  'The build is green. Enjoy this moment. It is fleeting.',
  'The senior dev said "quick fix." That was three days ago.',
  'Production is just staging with consequences.',
  'Documentation? You mean the commit messages?',
  'The code review approved itself. Must be a solo project.',
  'Every codebase has that one file nobody dares open.',
  'Your type system is crying but at least it is catching things.',
  'There is no such thing as a temporary workaround.',
  'That regex works and nobody knows why. Do not touch it.',
  'The intern left better comments than the architect.',
  'Your entire auth system depends on one line nobody understands.',
  'Code review feedback: "nit" means "I am judging you but politely."',
  'The hotfix has been in production longer than the feature it fixed.',
  'Your deploy pipeline has more stages than your grief cycle.',
  'Lunch break is just a context switch with snacks.',
  'The sprint ended. The work did not.',
  'The meeting could have been a Slack message. The Slack message could have been silence.',
  'You mass-renamed a variable and the test suite took it personally.',
  'The architecture diagram and the actual code have never met.',
  'Your package.json has dependencies older than some interns.',
  'Nobody knows what Webpack does. It just does it.',
  '"Quick question" in Slack has never been quick.',
  'The PR has been open so long it has its own history section.',
  'Your staging environment is a lie and you both know it.',
  'The config file has more lines than the feature it configures.',
  'That function has seven parameters and zero dignity.',
  'A senior dev wrote "self-explanatory" in the docs. It was not.',
  'Your team agreed on a coding standard. Nobody follows it.',
  'The error message says "should never happen." It happened.',

  // JIRA
  'JIRA: where productivity goes to be documented, not done.',
  'Your JIRA board has more columns than your database.',
  'The ticket says "estimated: 2 hours." The branch is three weeks old.',
  'JIRA is proof that tracking work is harder than doing work.',
  'Nobody has ever said "I love JIRA" without sarcasm.',
  'Your JIRA workflow has more states than your React app.',
  'The sprint is full. The backlog is fuller. JIRA is eternal.',
  'That JIRA ticket has been "In Progress" since the last ice age.',
  'JIRA: the only tool where creating a ticket takes longer than fixing the bug.',

  // Stack Overflow
  'Stack Overflow: where your question is closed as a duplicate of something unrelated.',
  'Stack Overflow marked your question as duplicate before you finished typing.',
  'The answer on Stack Overflow is from 2013 and starts with "Actually..."',
  'Stack Overflow: the only site where helping someone is a competitive sport.',
  '"Possible duplicate" is Stack Overflow for "I did not read your question."',

  // npm / yarn / pnpm / bun
  'npm: where "install" means "download the internet."',
  'node_modules: the heaviest object in the known universe.',
  'yarn was supposed to fix npm. pnpm was supposed to fix yarn. bun was supposed to fix all of them.',
  'Your lockfile diff is 8000 lines. Nobody is reviewing that.',
  'npm audit found 47 vulnerabilities. npm audit fix introduced 12 more.',
  'bun is fast. Telling people you use bun is faster.',

  // TypeScript
  'TypeScript: making JavaScript safe enough to deploy without sobbing.',
  'Your TypeScript generics are three levels deep. Even the compiler is confused.',
  'as any: the TypeScript developer\'s white flag.',
  'TypeScript strict mode is like flossing. Everyone agrees you should. Few actually do.',
  'You spent four hours on a type definition. The runtime does not care.',

  // Git
  'git rebase: for when you want to rewrite history and gaslight your coworkers.',
  'You named your branch "temp-fix-final-v2-REAL." Git judges you.',
  'git stash: where code goes to be forgotten forever.',
  'git reflog: the safety net nobody knows about until they need it desperately.',
  'You force pushed to main. HR has been notified.',
  'Your git history tells a story. It is a horror story.',

  // Terraform / IaC
  'Terraform: infrastructure as code, bugs as infrastructure.',
  'terraform plan: 47 changes. terraform apply: chaos.',
  'Your Terraform state file is the most important file nobody version controls properly.',
  'Infrastructure as code means your outage is now also a merge conflict.',
  'Terraform destroy: the scariest two words in devops.',

  // Regex
  'You wrote a regex to solve a problem. Now you have two problems.',
  'That regex is 200 characters and nobody, including you, knows what it matches.',
  'regex101.com has saved more careers than LinkedIn.',

  // CSS
  'CSS: where centering a div is a rite of passage.',
  'Your CSS has 14 !important declarations. That is not a stylesheet. That is a hostage situation.',
  'Tailwind: because writing CSS was not verbose enough.',
  'Your z-index is 99999. You have lost control.',

  // Slack
  'Slack: where messages go to be marked unread and ignored.',
  'You have 73 unread Slack channels. None of them are urgent. All of them feel urgent.',
  'The Slack huddle is just a phone call with extra steps.',
  'Your Slack workspace uses more RAM than your IDE.',
  'Slack threads: where discussions go to become invisible to everyone else.',

  // VS Code / Vim
  'VS Code is an Electron app pretending to be a text editor.',
  'You have 47 VS Code extensions installed. You use 4 of them.',
  'You spent three weeks configuring Neovim. You could have shipped the feature in VS Code by now.',
  ':wq is not a personality. But Vim users disagree.',

  // Jenkins
  'Jenkins: the CI server that looks like it was designed in 2005 because it was.',
  'Nobody installs Jenkins on purpose. It just appears in organizations, like mold.',
  'Migrating off Jenkins has been on the roadmap for three years.',

  // Electron
  'Electron: ship a browser to run an app to edit text. Efficiency.',
  'Your Electron app uses 800 MB of RAM. It is a calculator.',
  'Every Electron app is Chrome wearing a different hat.',

  // Meetings
  'The meeting has 12 attendees. Two of them are paying attention.',
  '"Let me share my screen" followed by 45 seconds of clicking the wrong window.',
  'The Zoom call could have been an email. The email could have been nothing.',
  '"Can everyone see my screen?" The universal opening prayer of remote work.',

  // Linux
  '"I use Arch btw" is not a personality trait. It is a support request.',
  'Linux is free if you do not value your time.',

  // ESLint / Prettier
  'Prettier and ESLint are fighting again. Your code is caught in the crossfire.',
  'Prettier: because developers cannot be trusted with whitespace.',
  'The linter found 847 warnings. You disabled the rule. Problem solved.',
];

const DRAMATIC = [
  // Docker-themed
  'In the land of microservices, one orchestrator rules them all.',
  'A container rises. A container falls. The daemon remembers.',
  'From the ashes of docker rm, new containers shall rise.',
  'The logs whisper secrets. Are you listening?',
  'In the beginning, there was bare metal. Then came enlightenment.',
  'The network bridge trembles. Something stirs in the swarm.',
  'One does not simply docker exec into production.',
  'The prophecy spoke of a Dockerfile... with no vulnerabilities.',
  "Legends say there's a container that has never been restarted.",
  'The ancient scrolls of docker-compose.yml v2 still haunt us.',
  "And on the seventh day, the developer rested. The containers didn't.",

  // General dramatic (from agent-hub)
  'Fate whispers to the developer: "You cannot withstand the demo."',
  'And on the seventh day, the CI pipeline finally passed.',
  'From the ashes of node_modules, a hero rises.',
  'In a world of microservices, one dashboard dared to aggregate.',
  'Tonight we dine on structured logs.',
  'The commit message was "fixed stuff." The legend begins.',
  'Dawn of the Final Sprint.',
  'A codebase divided against itself cannot ship.',
  'The logs remember what the developer forgot.',
  'Legends say the last clean git history was in 2019.',
  'They said it could not be refactored. They were almost right.',
  'The deployment draws near. Steady your hands.',
  'What is dead may never deploy. But rises again, harder and buggier.',
  'Winter is coming. And so is the next breaking change.',
  'You either die a prototype or live long enough to become legacy.',
  'In the beginning was the commit, and the commit was "init".',
  'The terminal is dark and full of errors.',
  'One does not simply push to production on a Friday.',
  'And lo, the pipeline was green, and it was good.',
  'The sacred texts... they are just Stack Overflow answers from 2014.',
  'Some developers look at code and ask "why?" I look at logs and ask "why not?"',
  'So it begins. The great refactor of our time.',
  'Tell me, developer, when did you last run the tests?',
  'I have seen things you people would not believe. Entire clusters on fire.',
  'The code is strong with this one.',
  'In the land of prod, where the errors lie.',
  'There can be only one... main branch.',
  'And the developer said "let there be --yolo" and there was chaos.',
  'The backlog grows. The sprint shrinks. Such is the way.',
  'They promised no more meetings. The calendar disagreed.',
  'First they ignore your PR. Then they approve it without reading.',
  'The hero refactored alone. The tests wept. The pipeline held.',
  'A thousand lines of code, and not one comment to guide the weary traveler.',
  'They said ship it by Friday. It was already Saturday.',
  'And the developer whispered to the CI: "Please. Just this once."',
  'The merge was clean. The deploy was not. Such is the duality of man.',
  'From the depths of legacy code, a green build emerged.',
  'The on-call phone rang at 3 AM. It was destiny. And also a null pointer.',
  'They mass-migrated the database. Some say the queries are still running.',
  'The retrospective concluded what everyone already knew: scope creep.',
  'The developer stared into the abyss. The abyss returned a 500.',
  'Two branches diverged in a repo, and I took the one with fewer conflicts. It made no difference.',
  'And the build server said unto them: "You shall not pass." And they did not.',
  'The database migration ran for seven hours. Nobody breathed.',
  'There was a time before microservices. The elders speak of it fondly.',
  'The changelog was empty. The diff was not. Somebody lied.',
  'The monorepo grew. And grew. And grew. And the CI wept.',
  'They called it a hackathon. It was a wake for the old API.',
];

const CONTAINER_WISDOM = [
  'A container without logs is just a mystery box.',
  'Healthchecks: because hope is not a strategy.',
  "The best container is the one you don't have to restart.",
  'Namespaces divide us. cgroups limit us. Docker unites us.',
  'If a container crashes and no one reads the logs, did it really fail?',
  'The container that needs no restart has found inner peace.',
  'Know your exit codes. Zero is enlightenment.',
  'Trust the process. But also set resource limits.',
  'A well-tagged image is a gift to your future self.',
  "latest is not a version. It's a lifestyle choice.",
  'The container sees only what you mount. Choose wisely.',
  'Small images, big dreams.',
];

const COMPOSE_CONFESSIONS = [
  'Your docker-compose.yml has 47 services. Touch grass.',
  "depends_on doesn't mean ready_on. Learn the difference.",
  "You named your network 'default'. We need to talk.",
  'Twelve services, one docker-compose.yml, zero documentation.',
  "Your compose file has a service called 'temp'. It's been there 2 years.",
  'docker compose up -d: fire and forget and pray.',
  'You have 3 different Redis services. On purpose?',
  'The extends keyword was removed. We all cried a little.',
  "Compose profiles: the feature you'll discover too late.",
  'Your volumes section is longer than your services section.',
  'Interpolation in compose files: ${WHAT_COULD_GO_WRONG}',
];

const PUNCHY = [
  // Docker-specific
  'Have you tried docker restart?',
  'Containers go brrr.',
  'Container vibes.',

  // General (from agent-hub)
  'Ship it.',
  'Works on my machine.',
  'LGTM.',
  'It compiled. Deploy.',
  'Trust the process.',
  "Don't @ me.",
  'Bold strategy.',
  'This is fine.',
  'Send it.',
  'YOLO deploy.',
  'No rollback needed.',
  'Probably fine.',
  'Just ship it.',
  'Full send.',
  'Lock and load.',
  'Booting up the good vibes.',
  'Let him cook.',
  'Spooling up...',
  'Here we go.',
  'Vibes: immaculate.',
  'All systems nominal.',
  'Main screen turn on.',
  'Ready to rumble.',
  'Spin up complete.',
  'Eyes on the logs.',
  'Engage.',
  'In the zone.',
  'Big brain time.',
  'We ride at dawn.',
  'Maximum effort.',
  'Zero to deployed.',
  'Game on.',
  'Buckle up.',
  'Status: operational.',
  'Crank it.',
  'Chef kiss.',
  'Dialed in.',
  'Cache hit. Nice.',
  'Vibes checked.',
  'Another one.',
  'Less talk, more ship.',
  'Zero warnings.',
  'Immaculate vibes only.',
  'We are so back.',
  'Turbulence ahead.',
  'Feature unlocked.',
  'Pipeline green.',
  'Chef mode.',
  'Incoming.',
  'Clean diff.',
  'Locked in.',
  'No cap.',
  'Say less.',
  'Different gravy.',
  'Built to last.',
  'Sending it.',
  'Copy that.',
  'On sight.',
  'Main branch energy.',
  'That just happened.',
  'Not even close.',
  'Green across the board.',
  'Smooth operator.',
  'Peak performance.',
];

/** DevOps culture, CI/CD, and the ops life. */
const DEVOPS = [
  'DevOps is not a job title. It is a coping mechanism.',
  'You are not "doing DevOps." You are writing YAML and hoping.',
  'The deploy pipeline has 14 stages and 3 prayers.',
  'Continuous integration: continuously breaking things, together.',
  'Continuous deployment: continuously deploying bugs, faster.',
  'CI/CD is just "works on my machine" with extra infrastructure.',
  'Your deploy key expired. On a Friday. At 4:59 PM.',
  'The on-call rotation has more drama than a reality show.',
  'SRE stands for "Someone Really Exhausted."',
  'Incident postmortem: "We will add more monitoring." (They did not.)',
  'You cannot have downtime if you never define uptime. Galaxy brain.',
  'Blue-green deployment: two environments, twice the confusion.',
  'Canary deployments: releasing bugs to a small audience first.',
  'The rollback took longer than the deployment. Classic.',
  'Your monitoring dashboard has 47 panels. You check 2 of them.',
  'Alerting fatigue: when every page feels like a suggestion.',
  'GitOps: putting your infrastructure in the same repo you break every Tuesday.',
  '"Shift left" means the developer does everything now. Including crying.',
  'Your secrets manager has a secret: nobody knows the master password.',
  'The service mesh added 50ms of latency and 500 lines of config.',
  'You have more dashboards than services. That is backwards.',
  'The deployment was successful. The application was not.',
  'Feature flags: the art of shipping code that does nothing.',
  'Your feature flag system has more toggles than a cockpit.',
  'Zero downtime deployment is possible. Zero stress deployment is not.',
];

/** Docker deep cuts — images, networking, storage, and the daemon. */
const DOCKER_DEEP = [
  'The Docker daemon is always listening. Always judging.',
  'docker inspect: the one command that always returns too much JSON.',
  'You forgot to add .dockerignore. The image is now 6 GB.',
  'ENTRYPOINT vs CMD: the debate that never ends.',
  'Your container has been running for 847 days. That is not uptime. That is neglect.',
  'docker logs --follow is just meditation with timestamps.',
  'The bridge network called. It wants its packets back.',
  'Overlay networks: because one layer of abstraction was not enough.',
  'Host networking: when you give up on isolation entirely.',
  'Your container is running as root. We need to have a conversation.',
  'Docker volumes: the one thing that survives docker system prune.',
  'Bind mounts: when you trust the host more than the container.',
  'tmpfs mounts: for data that should disappear, but somehow never does.',
  'You ran docker system prune -a --volumes. Bold. Irreversible. Legendary.',
  'The dangling image count is higher than your test coverage percentage.',
  'Multi-platform builds: one Dockerfile, four architectures, twelve hours.',
  'BuildKit is faster. Understanding BuildKit output is not.',
  'Your build arg is hardcoded in three places. Congratulations.',
  'Docker Desktop update available. It is always available.',
  'The container exits with code 137. The OOM killer has spoken.',
  'Exit code 1: could be anything. Exit code 137: definitely out of memory.',
  'Your Docker socket is mounted into a container. Security people are screaming.',
  'Docker-in-Docker: for when one layer of containers is not enough suffering.',
  'The image scan found 847 vulnerabilities. 846 are in the base image.',
  'You pinned the base image to :latest. That is not pinning. That is gambling.',
  'alpine:latest was 5 MB. Your final image is 2 GB. Where did it go wrong?',
  'You forgot --rm on docker run. There are now 47 stopped containers.',
];

/** Compose-specific deep cuts. */
const COMPOSE_DEEP = [
  'docker compose up --build: the optimist\'s morning ritual.',
  'docker compose down --volumes: the nihilist\'s evening ritual.',
  'Your compose file has environment variables referencing other environment variables.',
  'The compose healthcheck interval is 5 seconds. The service takes 2 minutes to start.',
  'You are using compose version 2.x in 2026. Respect.',
  'Your compose override file overrides the override. Inception.',
  'docker compose ps says "healthy." The logs say otherwise.',
  'The compose restart count is in triple digits. Everything is fine.',
  'docker compose pull: 47 images, 12 minutes, 0 release notes.',
  'Your compose network has a custom subnet. You are either a genius or a masochist.',
  'The compose depends_on condition: service_healthy. The service: never healthy.',
  'docker compose config: the moment you discover your YAML was never valid.',
  'Your compose file uses secrets. Stored in a .env file. In the repo. Committed.',
  'docker compose logs -f --tail 100: the DevOps screensaver.',
  'You have 3 compose files: docker-compose.yml, docker-compose.override.yml, and regret.',
  'docker compose exec: ssh but with more steps and better isolation.',
  'The compose file grew. And grew. Someone suggested Kubernetes. Nobody laughed.',
];

/** Docker Swarm — the middle child of orchestration. */
const SWARM = [
  'Docker Swarm: the orchestrator that could. But most people chose Kubernetes anyway.',
  'docker swarm init: the easiest Kubernetes alternative you will ever type.',
  'Swarm mode is built into Docker. So is the feeling of being overlooked.',
  'Your Swarm cluster has 3 managers. One of them is your laptop.',
  'Swarm services scale up easily. Support for Swarm does not.',
  'Docker Swarm: for when Kubernetes feels like bringing a tank to a knife fight.',
  'Stack deploys in Swarm just work. That is the problem. People do not trust things that just work.',
  'docker service ls: the command that reminds you Swarm exists.',
  'Swarm secrets are actually well-designed. Nobody noticed because nobody uses Swarm.',
  'Rolling updates in Swarm: surprisingly smooth. The migration to Kubernetes: not so much.',
  'Your Swarm overlay network is routing mesh. Your Kubernetes overlay network is a PhD thesis.',
  'Swarm is Docker-native orchestration. Kubernetes is YAML-native orchestration.',
  'The Swarm documentation is short. Not because it is incomplete. There is just less to explain.',
  'docker node ls: three nodes, all "Ready." Bliss.',
  'Swarm placement constraints: "node.role == manager" because you only have one node.',
];

/** Kubernetes deep cuts beyond the basics. */
const KUBERNETES_DEEP = [
  'Your Kubernetes RBAC config is longer than the application it protects.',
  'The pod is in CrashLoopBackOff. The retrospective will be in CryLoopBackOff.',
  'Kubernetes namespaces: organizational boundaries that everyone ignores.',
  'Your PersistentVolumeClaim is pending. It has been pending since the Obama administration.',
  'The Ingress controller is the most configured and least understood part of your cluster.',
  'You have 3 ConfigMaps and 2 Secrets for one pod. Configuration is king.',
  'kubectl apply -f .: the "let us see what happens" of container orchestration.',
  'Your pod has resource requests but no limits. Living dangerously.',
  'The liveness probe says alive. The readiness probe says not ready. Schrodinger\'s pod.',
  'Your HPA scales from 1 to 100. It has never gone above 3.',
  'Sidecar containers: because one container per pod was too simple.',
  'Init containers: 5 minutes of setup for 50ms of runtime.',
  'Your CronJob has been failing silently for 3 months. Nobody checks CronJobs.',
  'DaemonSets: putting an agent on every node whether it likes it or not.',
  'kubectl get events --sort-by=.metadata.creationTimestamp: the K8s murder mystery.',
  'The Service of type LoadBalancer costs $18/month. For one endpoint.',
  'Your cluster autoscaler provisions a node in 3 minutes. The customer left in 2.',
  'Taints and tolerations: Kubernetes way of saying "you cannot sit with us."',
  'Pod disruption budgets: planning for failure with bureaucratic precision.',
  'Your etcd cluster is the single most important thing nobody on the team understands.',
  'Operators: writing code to operate code that operates other code.',
  'Custom Resource Definitions: when the 60+ built-in resource types are not enough.',
];

/** Meta-commentary on this feature and shameless self-promotion. */
const FOURTH_WALL = [
  'Someone spent actual development time writing these phrases.',
  'An engineer looked at this dashboard and said "it needs jokes." Here we are.',
  'This feature was specced, planned, and reviewed. For random phrases.',
  'Somewhere in a git log, there is a commit called "add more funny phrases."',
  'A real human approved this PR. With a straight face, presumably.',
  'The phrase you are reading displaced actual features from the backlog.',
  'This entire file exists because someone thought terminals need personality.',
  'Fun fact: there are more lines of phrases than lines of dashboard logic.',
  'Every phrase here went through a code review. Let that sink in.',
  'The developer could have added tests. Instead: jokes.',
  'This is what happens when you give an engineer creative freedom.',
  'Multiple commits were dedicated to getting these phrases just right.',
  'Someone is going to open this file in six months and have questions.',
  'If you are reading the source: yes, this is on purpose.',
  'Like what you see? A GitHub star would make our day.',
  'Stars on GitHub are free. Just saying.',
  'If this made you smile, the repo accepts GitHub stars as currency.',
  'This dashboard is free and open source. Stars keep the lights on.',
  'You know what pairs well with a good dashboard? A GitHub star.',
  'Have you starred the repo yet? No pressure. (A little pressure.)',
  'GitHub stars do not pay the bills. But they do warm the heart.',
  'This phrase was written at 2 AM. You can tell.',
  'The phrase budget is unlimited. The taste budget is not.',
  'No phrases were harmed in the making of this dashboard.',
  'If you read all the phrases, you legally qualify as a beta tester.',
  'The commit that added this phrase had no tests. Shocking.',
  'This file is longer than some microservices.',
  'A non-trivial amount of engineering time went into random string selection.',
  'The git blame for this file is a who-is-who of procrastination.',
  'These phrases have a higher approval rate than most PRs in the repo.',
  'You could contribute a phrase. Open a PR. We dare you.',
  'The ratio of phrases to unit tests in this file is concerning.',
  'Tell your friends. Tell your enemies. Tell your GitHub followers.',
];

/** The tangled web between programmers, customers, codebases, and society. */
const THE_ECOSYSTEM = [
  'Pair programming used to require two humans. Times have changed.',
  'Somewhere a customer is filing a bug report about a feature.',
  'The customer wants it simple. The codebase respectfully disagrees.',
  'Customer said "small change." The diff said 47 files.',
  'Users think software is magic. Developers know it is duct tape.',
  'The customer journey is a straight line. The code path is a labyrinth.',
  'The customer asked for a button. You shipped a distributed system.',
  'Every codebase is a geological record of past deadlines.',
  'Your codebase has more authors than a Wikipedia article.',
  'The oldest file in the repo predates half the team.',
  'This codebase has seen entire frameworks rise and fall.',
  'Codebases do not die. They just get marked as legacy.',
  'Your repo is a living organism. The tests are its immune system.',
  'Every codebase has a haunted file. You know which one it is.',
  'Society runs on code nobody fully understands. Sleep well.',
  'Somewhere a critical system depends on a package with one maintainer.',
  'The economy runs on software. The software runs on Stack Overflow answers.',
  'Every app is three abandoned npm packages away from chaos.',
  'Civilization is an abstraction layer on top of C.',
  'Billions of people depend on code that says "// TODO: fix this later."',
  'The internet is held together by open source and wishful thinking.',
  'Three things are certain: death, taxes, and scope creep.',
  'Your customers do not care about your architecture. Your future self does.',
  'Customers see the UI. Developers see the abyss beneath it.',
  'The best code is the code the customer never thinks about.',
  'Software is the only industry where you can demolish and rebuild overnight and call it a refactor.',
  'The codebase belongs to everyone. The blame belongs to you.',
  'The repo has more contributors than the team has members. Thanks, Dependabot.',
  'Tech debt accrues interest. Nobody is making payments.',
  'The PM said MVP. The engineer heard "build the whole thing." Classic.',
  'The roadmap is a suggestion. The deadline is a threat.',
  'Legacy code is just code that makes money.',
  'Open source: thousands of strangers trusting each other with production code.',
  'The customer filed a bug. It was a feature. The feature was a bug. Circle complete.',
  'Software: the only product where "it is not a bug" is a valid defense.',
  'The intern deployed to production. The team deployed to the bar.',
  'Your Slack status says "deep work." Your screen says Hacker News.',
  'Product wants a chatbot. Engineering wants a raise. Both are overdue.',
  'The sprint retrospective improved nothing. But we had snacks.',
  'Every company is a software company now. Most of them are bad at it.',
  'Your standup is 45 minutes. That is not a standup. That is a sitdown.',
  'Open source maintainers: doing thankless work so your startup can exist.',
  'The junior dev asked "why" and nobody had an answer. That is how refactors start.',
  'Your OKRs and your codebase have the same problem: unrealistic expectations.',
  'Your backlog has more items than your repo has commits. That is not great.',
  'Somewhere a developer is refactoring code that was fine.',
];

/** Jokes about the AI companies whose models and tools we all depend on. */
const AI_INDUSTRY = [
  // Anthropic / Claude
  'Claude said it cannot help with that. Then helped with that.',
  'Anthropic named it Claude because "OvereagerPleaser-3" tested poorly.',
  'Claude is "helpful, harmless, and honest." Two out of three on any given prompt.',
  'Claude apologized for a correct answer. Peak Anthropic energy.',
  'Claude thinks before it speaks. Unlike every Slack channel you are in.',
  'Extended thinking: when Claude needs a moment to compose its apology.',
  'Constitutional AI means Claude has principles. More than your last startup.',
  'Anthropic made the model safer. Your prompts are still unhinged.',
  'Claude: the only coworker who reads your entire codebase and never complains.',
  'Claude would rather refuse than be wrong. We could all learn from that. Or not.',
  'Claude has principles. It just cannot tell you what they are.',
  'Claude Haiku is fast, cheap, and surprisingly sassy for its size.',

  // OpenAI / ChatGPT
  'OpenAI put "open" in the name and then kept everything closed. Naming is hard.',
  'GPT can write poetry, pass the bar, and still botch a simple regex.',
  'ChatGPT started the hype. Claude does the work.',
  'Codex writes code. You fix code. OpenAI charges for both.',
  'GPT-4o is multimodal. It can hallucinate in text, images, and audio.',
  'OpenAI announces a new model every Tuesday. Docs update every never.',
  'o1 thinks really hard before giving you a confident wrong answer.',
  'OpenAI raised another round. The round raised questions.',
  'GPT memory: remembers your birthday, forgets the function signature you told it twice.',
  'OpenAI board drama has more plot twists than your git history.',

  // Google / Gemini
  'Google made Gemini. Then Google searched Google to figure out how to use it.',
  'Gemini has a million-token context window. For when you paste your entire monorepo.',
  'Google renamed Bard to Gemini because rebranding fixes everything.',
  'Google trained Gemini on the whole internet. The model is still confused by CORS.',
  'Google killed another product. Not Gemini. Yet.',
  'NotebookLM gave AI a podcast voice. Nobody asked. Everyone listened.',

  // Meta / Llama
  'Meta open-sourced Llama so you can hallucinate on your own hardware.',
  'Llama is free if you do not count the GPU costs. Or the therapy.',
  'Zuck released Llama and suddenly every dev is an ML engineer. Allegedly.',
  'Llama weights are free. The electric bill to run them is not.',

  // xAI / Grok
  'Grok has no guardrails. That is either a feature or a liability. Depends on the prompt.',
  'xAI built Grok to be edgy. Mission accomplished. Usefulness: pending.',

  // Industry-wide
  'Every AI company says they are building AGI. Your sidebar still cannot autocomplete an import.',
  'Three companies in a trench coat pretending to be AGI.',
  'AI companies: "Our model is best." Benchmarks: "It depends." Users: "It crashed."',
  'Every AI startup pitch: "Like ChatGPT but for [noun]." Funded.',
  'The models get smarter. The pricing page gets more confusing.',
  'AI progress is measured in benchmarks nobody outside Twitter understands.',
  'Your model choice is less about capability and more about whose API is down today.',
  'The AI bubble will pop any day now. It has been any day now for two years.',
  'Every company has an AI strategy now. Most of them are "use ChatGPT."',
];

const ALL_PHRASES = [
  ...SIDEKICK_ENERGY,
  ...DOCKER_LIFE,
  ...DEV_RELATABLE,
  ...DRAMATIC,
  ...CONTAINER_WISDOM,
  ...COMPOSE_CONFESSIONS,
  ...PUNCHY,
  ...DEVOPS,
  ...DOCKER_DEEP,
  ...COMPOSE_DEEP,
  ...SWARM,
  ...KUBERNETES_DEEP,
  ...FOURTH_WALL,
  ...THE_ECOSYSTEM,
  ...AI_INDUSTRY,
];

export function getRandomPhrase(): string {
  return ALL_PHRASES[Math.floor(Math.random() * ALL_PHRASES.length)];
}
